/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "f446re_gpio.h"
#include "f446re_rcc.h"

int main(void)
{
	//Enable clock for GPIOA
	RCC->AHB1ENR = RCC_AHB1ENR_GPIOA;

	//Set pin 5 at GPIOA MODER register as output
	GPIOA->MODER |= (GPOM_MODE << 10);

	while(1){
		//Setting pin5 as high
		GPIOA->ODR |= (1 << 5);

		//Set low pin5
		GPIOA->ODR |= (1 << 5);

	}
}
